name: Docgen

on:
  workflow_call:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v4
      - name: panvimdoc
        uses: kdheepak/panvimdoc@v4.0.0
        with:
          vimdoc: ddu-filter-zf
          version: "Vim/Neovim"
          toc: false
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto generate docs"
          branch: ${{ github.head_ref }}
