name: Release

on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    name: Release

    if: ${{ github.repository_owner == 'hasundue' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.36.1 # @denopendabot denoland/deno

      - name: Check if release is needed
        id: check
        uses: hasundue/denomantic-release@0.10.0
        with:
          denopendabot: disabled
          options: --dry-run

      - name: Setup Zig
        if: ${{ steps.check.outputs.version && !steps.check.output.needs_update }}
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0 # @denopendabot ziglang/zig

      - name: Build assets
        id: build
        run: deno task build x86_64-linux x86_64-windows x86_64-macos

      - name: Release
        if: ${{ steps.build.outcome == 'success' }}
        uses: hasundue/denomantic-release@0.10.0
        with:
          denopendabot: app
          assets: zf/libzf.so zf/zf.dll zf/libzf.dylib
          draft: true
