name: Test

on:
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Test

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        zig_ver: [ master, 0.10.1 ] # @denopendabot ziglang/zig

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig_ver }}

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.32.3 # @denopendabot denoland/deno

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache
        run: deno cache build.ts libzf.ts

      - name: Build
        run: deno task build

      - name: Test
        run: deno task test --coverage=./coverage

      - name: Create coverage report
        run: deno coverage ./coverage --lcov > ./coverage.lcov

      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.lcov
